sudo: required
services:
  - docker
before install:
  - docker build -t ashwani-m/react-docker -f Dockerfile.dev .
script:
  - docker run -e CI=true ashwani-m/react-docker npm run test
 deploy:
   provider: elasticbeanstalk
   region: "eu-west-1"
   app: "React-Docker"
   env: "ReactDocker-env"
   bucket_name: "elasticbeanstalk-eu-west-1-143607323522"
   bucket_path: "React-Docker"
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
     secure: "$AWS_SECRET_KEY"
